Troubleshot through several issues and now we can login a user and have the website display as such.
Three scary errors were
InvalidOperationException: No services for type. When initially adding if logic to _Layout.cshtml
HTTP ERROR 405. When Account Controller needed to have HttpPosts configured for SignIn, Register and Logout
Error with clicking LogIn with valid user, but nothing happened (signInManager.IsSignedIn(User) always returned False.) Troubleshot as detailed in _Layout.cshtml, turned out not bad.